services:
   zookeeper:
      image: confluentinc/cp-zookeeper:7.4.0
      ports:
         - "2181:2181"
      environment:
         ZOOKEEPER_CLIENT_PORT: 2181
         ZOOKEEPER_TICK_TIME: 2000

   kafka:
      image: confluentinc/cp-kafka:7.4.0
      depends_on:
         - zookeeper
      ports:
         - "9092:9092"
      environment:
         KAFKA_BROKER_ID: 1
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
         KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

   redis:
      image: redis:7-alpine
      ports:
         - "6379:6379"
      volumes:
         - redis_data:/data
      command: redis-server --appendonly yes

   frontend-react-websocket:
      build: ./frontend-react-websocket
      image: frontend-react-websocket-image
      ports:
         - "3000:80"
      depends_on:
         - java-spring-notification-service

   java-spring-notification-service:
      build:
         context: ./java-spring-notification-service
         dockerfile: Dockerfile
      image: java-spring-notification-service-image
      environment:
         - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/${DB_NAME}
         - SPRING_DATASOURCE_USERNAME=${DB_USER}
         - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
         - REDIS_HOST=redis
      ports:
         - "8080:8080"
      depends_on:
         - kafka
         - redis

   python-fastapi-stock-service:
      build:
         context: ./python-fastapi-stock-service
         dockerfile: Dockerfile
      image: python-fastapi-stock-service-image
      environment:
         - DB_HOST=<db_container_name>
         - DB_USER=${DB_USER}
         - DB_PASSWORD=${DB_PASSWORD}
         - DB_NAME=${DB_NAME}
         - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      ports:
         - "50051:50051"
      depends_on:
         - kafka

volumes:
   redis_data: